In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_predict

sc = StandardScaler()
#leo variables
X_train = pd.read_csv("X_train_unigram.csv", sep=",")
X_test = pd.read_csv("X_test_unigram.csv", sep=",")
y_train = pd.read_csv("y_train_unigram.csv", sep=",")
y_test = pd.read_csv("y_test_unigram.csv", sep=",")

scaler = MinMaxScaler(feature_range=(0, 1))
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=1000,bootstrap = True,oob_score=True, n_jobs=4)
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train.values.ravel())

y_pred=clf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
#Verifico la matriz de Confusión
print(confusion_matrix(y_test,y_pred))
#Calculo la precisión del modelo
df3 = pd.DataFrame(classification_report(y_test, y_pred,output_dict=True))
df3


Accuracy: 0.5955555555555555
[[48 10 17]
 [19 49  7]
 [32  6 37]]


0          1          2  accuracy   macro avg  weighted avg
precision   0.484848   0.753846   0.606557  0.595556    0.615084      0.615084
recall      0.640000   0.653333   0.493333  0.595556    0.595556      0.595556
f1-score    0.551724   0.700000   0.544118  0.595556    0.598614      0.598614
support    75.000000  75.000000  75.000000  0.595556  225.000000    225.000000

In [10]:
from sklearn.metrics import precision_score
from sklearn.utils import shuffle
dataset = pd.read_csv("Features unigrama.csv", sep=",", low_memory=False)
shuffle(dataset)
y = dataset.Label
X = dataset.drop('Label', axis=1)
scaler = MinMaxScaler(feature_range=(0, 1))
X = scaler.fit_transform(X)
y_pred = cross_val_predict(clf, X, y, cv=5, n_jobs=4)
print('Matriz de Confusión:')
print(confusion_matrix(y,y_pred))
#Calculo la precisión del modelo
precision = precision_score(y, y_pred,average='weighted')
print('Precisión del modelo:')
print(precision)

df2 = pd.DataFrame(classification_report(y_test, y_pred,output_dict=True))
df2

Matriz de Confusión:
[[188  15  47]
 [104 125  21]
 [123  18 109]]
Precisión del modelo:
0.6199901659128827
              precision    recall  f1-score   support

           0       0.45      0.75      0.57       250
           1       0.79      0.50      0.61       250
           2       0.62      0.44      0.51       250

    accuracy                           0.56       750
   macro avg       0.62      0.56      0.56       750
weighted avg       0.62      0.56      0.56       750



In [11]:
dataset = pd.read_csv("features bigram.csv", sep=",", low_memory=False)
shuffle(dataset)
y = dataset.Label
X = dataset.drop('Label', axis=1)
scaler = MinMaxScaler(feature_range=(0, 1))
X = scaler.fit_transform(X)
y_pred = cross_val_predict(clf, X, y, cv=5, n_jobs=4)
print('Matriz de Confusión:')
print(confusion_matrix(y,y_pred))
#Calculo la precisión del modelo
precision = precision_score(y, y_pred,average='weighted')
print('Precisión del modelo:')
print(precision)

print(classification_report(y, y_pred))


Matriz de Confusión:
[[118 119  13]
 [ 88 154   8]
 [108 126  16]]
Precisión del modelo:
0.3980645076856944
              precision    recall  f1-score   support

           0       0.38      0.47      0.42       250
           1       0.39      0.62      0.47       250
           2       0.43      0.06      0.11       250

    accuracy                           0.38       750
   macro avg       0.40      0.38      0.33       750
weighted avg       0.40      0.38      0.33       750



In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

sc = StandardScaler()
#leo variables
X_train = pd.read_csv("X_train_bigram.csv", sep=",")
X_test = pd.read_csv("X_test_bigram.csv", sep=",")
y_train = pd.read_csv("y_train_bigram.csv", sep=",")
y_test = pd.read_csv("y_test_bigram.csv", sep=",")
scaler = MinMaxScaler(feature_range=(0, 1))
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=1000,bootstrap = True,oob_score=True, n_jobs=4)
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train.values.ravel())

y_pred=clf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
#Verifico la matriz de Confusión
print(confusion_matrix(y_test,y_pred))
#Calculo la precisión del modelo
df4 = pd.DataFrame(classification_report(y_test, y_pred,output_dict=True))
df4

Accuracy: 0.47333333333333333
[[34 13  3]
 [19 28  3]
 [31 10  9]]


0          1          2  accuracy   macro avg  weighted avg
precision   0.404762   0.549020   0.600000  0.473333    0.517927      0.517927
recall      0.680000   0.560000   0.180000  0.473333    0.473333      0.473333
f1-score    0.507463   0.554455   0.276923  0.473333    0.446280      0.446280
support    50.000000  50.000000  50.000000  0.473333  150.000000    150.000000

In [23]:
with pd.ExcelWriter("output.xlsx", engine="openpyxl", mode="a") as writer:
    df3.to_excel(writer, sheet_name='RF unigramas')
    df4.to_excel(writer, sheet_name='RF bigramas')